[workspace]

members = [
    "libraries/tx_processor",
    "libraries/blockchain_api",
    "libraries/common",
	"libraries/dreamdexer_psql",
	"services/evm-collector",
	"services/evm-processor",
	"services/evm-loader",
	"services/evm-syncer"
]